# Generated by Django 3.0.7 on 2020-09-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='t_create',
        ),
        migrations.RemoveField(
            model_name='article',
            name='t_published',
        ),
        migrations.RemoveField(
            model_name='article',
            name='t_update',
        ),
        migrations.AddField(
            model_name='article',
            name='create',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
